const datosLecciones = {
  lecciones: [
    {
      id: 1,
      nombre: "leccion 1",
      palabras: [
{aleman: "der Muskel", espanol: "el músculo"},
{aleman: "das Tattoo", espanol: "el tatuaje"},
{aleman: "das Piercing", espanol: "el piercing"},
{aleman: "das Make-up", espanol: "el maquillaje"},
{aleman: "der Stil", espanol: "el estilo"},
{aleman: "gut aussehen", espanol: "ser guapo/a"},
{aleman: "der Schmuck", espanol: "las joyas, la bisutería"},
{aleman: "die Frisur", espanol: "el peinado"},
{aleman: "altmodisch", espanol: "pasado/a de moda"},
{aleman: "schick", espanol: "elegante"},
{aleman: "hübsch", espanol: "bonito/a"},
{aleman: "zuordnen, ordnete zu, hat zugeordnet", espanol: "relacionar"},
{aleman: "die Schulter", espanol: "el hombro"},
{aleman: "der Hut", espanol: "el sombrero"},
{aleman: "sich die Zähne putzen, putzte sich die Zähne, hat sich die Zähne geputzt", espanol: "lavarse los dientes"},
{aleman: "sich die Haare färben, färbte sich die Haare, hat sich die Haare gefärbt", espanol: "teñirse el pelo"},
{aleman: "sich umziehen, zog sich um, hat sich umgezogen ", espanol: "cambiarse de ropa"},
{aleman: "sich schminken, schminkte sich, hat sich geschminkt", espanol: "maquillarse"},
{aleman: "sich rasieren, rasierte sich, hat sich rasiert", espanol: "afeitarse"},
{aleman: "sich waschen, wusch sich, hat sich gewaschen", espanol: "lavarse"},
{aleman: "sich die Haare schneiden, schnitt sich die Haarre, hat sich die Haare geschnitten", espanol: "cortarse el pelo"},
{aleman: "sich kämmen, kämmte sich, hat sich gekämmt", espanol: "peinarse"},
{aleman: "die Klamotten", espanol: "la ropa"},
{aleman: "ständig", espanol: "constantemente"},
{aleman: "die Creme", espanol: "la crema"},
{aleman: "die Drogerie", espanol: "la droguería"},
{aleman: "aufregen, regte auf, hat aufgeregt", espanol: "sacar de quicio"},
{aleman: "ausschließlich", espanol: "únicamente"},
{aleman: "der Monat", espanol: "el mes"},
{aleman: "der Kamm", espanol: "el peine"},
{aleman: "die Bürste", espanol: "el cepillo"},
{aleman: "die Hygiene", espanol: "la higiene"},
{aleman: "die Badewanne", espanol: "la bañera"},
{aleman: "gründlich", espanol: "a fondo"},
{aleman: "die Zahnbürste", espanol: "el cepillo de dientes"},
{aleman: "die Zahnpasta", espanol: "la pasta de dientes"},
{aleman: "die Zahnspange", espanol: "el braquet"},
{aleman: "schief", espanol: "torcido/a"},
{aleman: "dauernd", espanol: "continuamente"},
{aleman: "die Lippe", espanol: "el labio"},
{aleman: "blass", espanol: "pálido/a"},
{aleman: "das Parfüm", espanol: "el perfume"},
{aleman: "das Motiv", espanol: "el motivo"},
{aleman: "aussuchen, suchte aus, hat ausgesucht", espanol: "elegir"},
{aleman: "erstellen, erstellte, hat erstellt", espanol: "crear"},
{aleman: "der Bart", espanol: "la barba"},
{aleman: "die Körperpflege", espanol: "la higiene corporal"},
{aleman: "die Tätigkeit", espanol: "la actividad"},
{aleman: "zweimal", espanol: "dos veces"},
{aleman: "das Beispiel", espanol: "el ejemplo"},
{aleman: "die Aussage", espanol: "la declaración"},
{aleman: "der Angeber", espanol: "el fanfarrón"},
{aleman: "posten, postete, hat gepostet", espanol: "publicar en internet"},
{aleman: "zusammenfassen, fasste zusammen, hat zusammengefasst", espanol: "resumir"},
{aleman: "die Muttersprache", espanol: "la lengua materna"},
{aleman: "weshalb", espanol: "por lo que"},
{aleman: "daher", espanol: "por eso"},
{aleman: "darum", espanol: "por eso"},
{aleman: "deswegen", espanol: "por eso"},
{aleman: "funktionieren, funktionierte, hat funktioniert", espanol: "funcionar"},
{aleman: "ergänzen, ergänzte, hat ergänzt", espanol: "completar"},
{aleman: "der Streit", espanol: "la discusión"},
{aleman: "die Überschrift", espanol: "el título"},
{aleman: "der Vergleich", espanol: "la comparación"},
{aleman: "perfekt", espanol: "perfecto/a"},
{aleman: "sich beschäftigen, beschäftigte sich, hat sich beschäftigt", espanol: "ocuparse"},
{aleman: "das Detail", espanol: "el detalle"},
{aleman: "die Erfahrung", espanol: "la experiencia"},
{aleman: "der Kommentar", espanol: "el comentario"},
{aleman: "bereits", espanol: "ya"},
{aleman: "tatsächlich", espanol: "realmente"},
{aleman: "produzieren, produzierte, hat produziert", espanol: "producir"},
{aleman: "gleichzeitig", espanol: "al mismo tiempo"},
{aleman: "kräftig", espanol: "fuerte"},
{aleman: "gar nicht", espanol: "en absoluto"},
{aleman: "stündlich", espanol: "cada hora"},
{aleman: "jedes Mal", espanol: "cada vez"},
{aleman: "absolut", espanol: "absolutamente"},
{aleman: "schlank", espanol: "delgado/a"},
{aleman: "flach", espanol: "plano/a"},
{aleman: "die Diät", espanol: "la dieta"},
{aleman: "abnehmen, nahm ab, hat abgenommen", espanol: "adelgazar"},
{aleman: "dünn", espanol: "delgado/a"},
{aleman: "ziemlich", espanol: "bastante"},
{aleman: "seltsam", espanol: "raro/a"},
{aleman: "äußerlich", espanol: "por fuera"},
{aleman: "die Eitelkeit", espanol: "la vanidad"},
{aleman: "der Wert", espanol: "el valor"},
{aleman: "ähnlich", espanol: "parecido/a"},
{aleman: "ausgefallen", espanol: "extravagante"},
{aleman: "anfangs", espanol: "al principio"},
{aleman: "mittlerweile", espanol: "entretanto"},
{aleman: "sich gewöhnen, gewöhnte sich, hat sich gewöhnt", espanol: "acostumbrarse a"},
{aleman: "behaupten, behauptete, hat behauptet", espanol: "sostener"},
{aleman: "beeinflussen, beeinflusste, hat beeinflusst", espanol: "influir"},
{aleman: "bestimmt", espanol: "seguramente"},
{aleman: "der Grund", espanol: "la razón"},
{aleman: "da", espanol: "porque"},
{aleman: "Sport treiben", espanol: "hacer deporte"},
{aleman: "zustimmen, stimmte zu, hat zugestimmt", espanol: "estar de acuerdo"},
{aleman: "widersprechen, widersprach, hat widersprochen", espanol: "llevar la contraria"},
{aleman: "recht haben", espanol: "tener razón"},
{aleman: "überzeugt sein", espanol: "estar convencido/a"},
{aleman: "stimmen", espanol: "ser cierto"},
{aleman: "Das stimmt.", espanol: "Es verdad."},
{aleman: "obwohl", espanol: "aunque"},
{aleman: "ungesund", espanol: "poco sano"},
{aleman: "das Geld", espanol: "el dinero"},
{aleman: "preiswert", espanol: "barato/a"},
{aleman: "das Kapitel", espanol: "el capítulo"},
{aleman: "besonders", espanol: "especial"}
]
    },
    {
      id: 2,
      nombre: "leccion 2",
      palabras: [
{aleman: "das Medium", espanol: "el medio de comunicación"},
{aleman: "das Netz", espanol: "la red"},
{aleman: "das Leben", espanol: "la vida"},
{aleman: "benutzen", espanol: "utilizar"},
{aleman: "das Fernsehen", espanol: "la televisión"},
{aleman: "vor", espanol: "antes"},
{aleman: "die Technik", espanol: "la tecnología, la electrónica"},
{aleman: "streamen", espanol: "hacer streaming"},
{aleman: "die Werbung", espanol: "la publicidad"},
{aleman: "nutzen", espanol: "aprovechar"},
{aleman: "Wie lange?", espanol: "¿Cuánto tiempo?"},
{aleman: "verzichten auf", espanol: "renunciar a"},
{aleman: "für", espanol: "para, por"},
{aleman: "höchstens", espanol: "como máximo"},
{aleman: "das Magazin", espanol: "la revista"},
{aleman: "erwarten", espanol: "esperar"},
{aleman: "herunterfahren", espanol: "apagar el ordenador"},
{aleman: "aufnehmen", espanol: "grabar"},
{aleman: "die Sendung", espanol: "el programa"},
{aleman: "der Wetterbericht", espanol: "el parte meteorológico"},
{aleman: "der Streamingdienst", espanol: "servicio de transmisión"},
{aleman: "ausdrucken", espanol: "imprimir"},
{aleman: "klicken", espanol: "clicar"},
{aleman: "kritisch", espanol: "crítico/a"},
{aleman: "die Hälfte", espanol: "la mitad"},
{aleman: "das Drittel", espanol: "el tercio"},
{aleman: "das Viertel", espanol: "el cuarto"},
{aleman: "das Fünftel", espanol: "el quinto"},
{aleman: "das Prozent", espanol: "el porcentaje"},
{aleman: "regelmäßig", espanol: "regular"},
{aleman: "bloß", espanol: "solamente"},
{aleman: "Zeit verbringen", espanol: "pasar tiempo"},
{aleman: "die Regel", espanol: "la regla"},
{aleman: "höflich", espanol: "educado/a"},
{aleman: "wenige", espanol: "pocos"},
{aleman: "die Grafik", espanol: "el gráfico"},
{aleman: "besitzen", espanol: "poseer"},
{aleman: "persönlich", espanol: "personal, personalmente"},
{aleman: "bloggen", espanol: "bloguear"},
{aleman: "senden", espanol: "enviar"},
{aleman: "die Schallplatte", espanol: "el disco de vinilo"},
{aleman: "die Kassette", espanol: "el casete"},
{aleman: "auswählen", espanol: "elegir"},
{aleman: "achten auf", espanol: "fijarse en"},
{aleman: "gehören", espanol: "pertenecer"},
{aleman: "tippen", espanol: "teclear"},
{aleman: "der Vorteil", espanol: "la ventaja"},
{aleman: "der Nachteil", espanol: "la desventaja"},
{aleman: "die Reihenfolge", espanol: "el orden"},
{aleman: "kaum", espanol: "apenas"},
{aleman: "der Kalender", espanol: "el calendario"},
{aleman: "eintragen", espanol: "inscribir"},
{aleman: "checken", espanol: "revisar"},
{aleman: "verbinden", espanol: "unir"},
{aleman: "bedienen", espanol: "atender"},
{aleman: "die Fernbedienung", espanol: "el mando a distancia"},
{aleman: "übernehmen", espanol: "hacerse cargo"},
{aleman: "die Heizung", espanol: "la calefacción"},
{aleman: "die Generation", espanol: "la generación"},
{aleman: "selten", espanol: "rara vez"},
{aleman: "sinnlos", espanol: "sin sentido"},
{aleman: "verrückt", espanol: "loco/a"},
{aleman: "der Pinguin", espanol: "el pingüino"},
{aleman: "überlegen", espanol: "reflexionar"},
{aleman: "die Daten", espanol: "los datos"},
{aleman: "der Hersteller", espanol: "el fabricante"},
{aleman: "verbessern", espanol: "mejorar"},
{aleman: "das Modell", espanol: "el modelo"},
{aleman: "die Zukunft", espanol: "el futuro"},
{aleman: "das Gefühl", espanol: "el sentimiento"},
{aleman: "allgemein", espanol: "generalmente"},
{aleman: "übrig sein", espanol: "sobrar"},
{aleman: "dringend", espanol: "urgentemente"},
{aleman: "wöchentlich", espanol: "semanalmente"},
{aleman: "sich melden", espanol: "levantar la mano"},
{aleman: "flexibel sein", espanol: "ser flexible"},
{aleman: "gebraucht", espanol: "usado/a"},
{aleman: "der Drucker", espanol: "la impresora"},
{aleman: "der Zustand", espanol: "el estado"},
{aleman: "bieten", espanol: "ofrecer"},
{aleman: "die Kamera", espanol: "la cámara"},
{aleman: "die Annonce", espanol: "el anuncio"},
{aleman: "einzeln", espanol: "individualmente"},
{aleman: "verschieden", espanol: "diferente"},
{aleman: "insgesamt", espanol: "en total"},
{aleman: "die Abkürzung", espanol: "la abreviatura"},
{aleman: "sich unterscheiden", espanol: "diferenciarse"},
{aleman: "mischen", espanol: "mezclar"},
{aleman: "dran sein", espanol: "tener el turno"},
{aleman: "motiviert", espanol: "motivado/a"},
{aleman: "erfahren sein", espanol: "ser experto/a"},
{aleman: "das Turnier", espanol: "el torneo"},
{aleman: "ausführen", espanol: "realizar"},
{aleman: "der Speicher", espanol: "la memoria"},
{aleman: "befehlen", espanol: "ordenar"},
{aleman: "der Befehl", espanol: "la orden"},
{aleman: "der Karton", espanol: "el cartón"},
{aleman: "aufheben", espanol: "coger del suelo"},
{aleman: "der Link", espanol: "el enlace"},
{aleman: "googeln", espanol: "googlear"},
{aleman: "die CD", espanol: "el CD"},
{aleman: "der Plattenspieler", espanol: "el tocadiscos"},
{aleman: "der Smartspeaker", espanol: "el altavoz inteligente"},
{aleman: "zu viert", espanol: "de cuatro en cuatro"},
{aleman: "die App", espanol: "la aplicación"},
{aleman: "real", espanol: "real"},
{aleman: "offline", espanol: "offline (fuera de línea)"}
]
    },
   {
      id: 3,
      nombre: "leccion 3",
      palabras: [
{aleman: "gemeinsam", espanol: "en común, juntos"},
{aleman: "die Mahlzeit", espanol: "la comida"},
{aleman: "normalerweise", espanol: "normalmente"},
{aleman: "das Dessert", espanol: "el postre"},
{aleman: "die Nachspeise", espanol: "el postre"},
{aleman: "die Hauptspeise", espanol: "el plato principal"},
{aleman: "die Vorspeise", espanol: "el primer plato"},
{aleman: "bitter", espanol: "amargo/a"},
{aleman: "salzig", espanol: "salado/a"},
{aleman: "die Zutat", espanol: "el ingrediente"},
{aleman: "sich ernähren", espanol: "alimentarse"},
{aleman: "häufig", espanol: "a menudo"},
{aleman: "die Dose", espanol: "la lata"},
{aleman: "der Essig", espanol: "el vinagre"},
{aleman: "der Honig", espanol: "la miel"},
{aleman: "die Packung", espanol: "el paquete"},
{aleman: "vorwärts", espanol: "adelante"},
{aleman: "stammen", espanol: "proceder"},
{aleman: "die Speise", espanol: "la comida"},
{aleman: "das Buffet", espanol: "el bufé"},
{aleman: "sich entscheiden", espanol: "decidirse"},
{aleman: "die Herkunft", espanol: "el origen"},
{aleman: "selber", espanol: "uno mismo"},
{aleman: "ursprünglich", espanol: "inicialmente"},
{aleman: "Armenien", espanol: "Armenia"},
{aleman: "unterstützen", espanol: "apoyar"},
{aleman: "die Organisation", espanol: "la organización"},
{aleman: "knapp", espanol: "escaso/a"},
{aleman: "optimistisch", espanol: "optimista"},
{aleman: "die Aktion", espanol: "la acción"},
{aleman: "traditionell", espanol: "tradicional"},
{aleman: "der Tanz", espanol: "el baile"},
{aleman: "eröffnen", espanol: "abrir"},
{aleman: "nah", espanol: "cerca"},
{aleman: "der Erfolg", espanol: "el éxito"},                
{aleman: "gelingen", espanol: "salir bien"},
{aleman: "die Liste", espanol: "la lista"},
{aleman: "ausgezeichnet", espanol: "excelente"},
{aleman: "zubereiten", espanol: "preparar"},
{aleman: "kompliziert", espanol: "complicado/a"},
{aleman: "satt", espanol: "satisfecho/a"},
{aleman: "das Hackfleisch", espanol: "la carne picada"},
{aleman: "die Zwiebel", espanol: "la cebolla"},
{aleman: "die Knoblauchzehe", espanol: "el diente de ajo"},
{aleman: "das Öl", espanol: "el aceite"},
{aleman: "die Margarine", espanol: "la margarina"},
{aleman: "die Paprika", espanol: "el pimiento"},
{aleman: "der Mais", espanol: "el maíz"},
{aleman: "die Gemüsebrühe", espanol: "el caldo de verduras"},
{aleman: "das Gewürz", espanol: "la especia"},
{aleman: "komplett", espanol: "completo/a"},
{aleman: "entsorgen", espanol: "desechar"},
{aleman: "der Schaden", espanol: "el daño"},
{aleman: "trotzdem", espanol: "sin embargo"},
{aleman: "strafbar", espanol: "sancionable"},
{aleman: "bestrafen", espanol: "castigar"},
{aleman: "der Ärger", espanol: "el enfado"},
{aleman: "das Gesetz", espanol: "la ley"},
{aleman: "der Politiker", espanol: "el político"},
{aleman: "fordern", espanol: "exigir"},
{aleman: "die Forderung", espanol: "la exigencia"},
{aleman: "die Bevölkerung", espanol: "la población"},
{aleman: "ernsthaft", espanol: "serio/a"},
{aleman: "anschaffen", espanol: "adquirir"},
{aleman: "öfter", espanol: "con frecuencia"},
{aleman: "die Limonade", espanol: "la limonada"},
{aleman: "besorgen", espanol: "conseguir"},
{aleman: "biologisch", espanol: "biológico/a"},
{aleman: "entstehen", espanol: "surgir"},
{aleman: "vor allem", espanol: "sobre todo"},
{aleman: "der Trend", espanol: "la tendencia"},
{aleman: "die Eröffnung", espanol: "la apertura"},
{aleman: "die Nachfrage", espanol: "la demanda"},
{aleman: "die Seife", espanol: "el jabón"},
{aleman: "das Waschmittel", espanol: "el detergente"},
{aleman: "sämtliche", espanol: "todos/as"},
{aleman: "die Methode", espanol: "el método"},
{aleman: "ökologisch", espanol: "ecológico/a"},
{aleman: "die Initiative", espanol: "la iniciativa"},
{aleman: "die Frucht", espanol: "la pieza de fruta"},
{aleman: "der Rat", espanol: "el consejo"},
{aleman: "das Gebäck", espanol: "las pastas"},
{aleman: "der Pfeffer", espanol: "la pimienta"},
{aleman: "das Kilogramm", espanol: "el kilogramo"},
{aleman: "das Pfund", espanol: "el medio kilo"},
{aleman: "zunächst", espanol: "al principio"},
{aleman: "die Pfanne", espanol: "la sartén"},
{aleman: "gießen", espanol: "verter"},
{aleman: "würzen", espanol: "condimentar"},
{aleman: "die Hitze", espanol: "el calor"},
{aleman: "eventuell", espanol: "a lo mejor"},
{aleman: "nochmals", espanol: "otra vez"},
{aleman: "Danke, gleichfalls!", espanol: "¡Gracias, igualmente!"},
{aleman: "genießen", espanol: "disfrutar de"},
{aleman: "gespannt", espanol: "intrigado/a"},
{aleman: "die Anleitung", espanol: "la introducción"},
{aleman: "der Pilz", espanol: "el hongo"},
{aleman: "die Möhre", espanol: "la zanahoria"},
{aleman: "die Aprikose", espanol: "el albaricoque"},
{aleman: "das Steak", espanol: "el bistec"},
{aleman: "die Schlagsahne", espanol: "la nata montada"},
{aleman: "die Schüssel", espanol: "el bol"},
{aleman: "das Mehl", espanol: "la harina"},
{aleman: "gering", espanol: "escaso/a"},
{aleman: "der Backofen", espanol: "el horno"},
{aleman: "die Soße", espanol: "la salsa"},
{aleman: "der Braten", espanol: "el asado"},
{aleman: "die Umwelt", espanol: "el medio ambiente"},
{aleman: "wohl", espanol: "probablemente"},
{aleman: "die Plastiktüte", espanol: "la bolsa de plástico"},
{aleman: "der Abfall", espanol: "la basura"},
{aleman: "das Haltbarkeitsdatum", espanol: "la fecha de caducidad"},
{aleman: "haltbar", espanol: "duradero/a"},
{aleman: "die Verpackung", espanol: "el embalaje"},
{aleman: "containern", espanol: "buscar en los contenedores"},
{aleman: "die Verschwendung", espanol: "el derroche"},
{aleman: "der Diebstahl", espanol: "el robo"},
{aleman: "der Dieb", espanol: "el ladrón"},
{aleman: "die Diebin", espanol: "la ladrona"},
{aleman: "stehlen", espanol: "robar"},
{aleman: "die Mülltonne", espanol: "el contenedor de basura"},
{aleman: "die Müllabfuhr", espanol: "la recogida de basura"},
{aleman: "landen", espanol: "ir a parar"},
{aleman: "sich eignen", espanol: "servir"},
{aleman: "irgendein", espanol: "cualquier"},
{aleman: "das heißt", espanol: "es decir"},
{aleman: "retten", espanol: "salvar"},
{aleman: "sobald", espanol: "tan pronto como"},
{aleman: "ablaufen", espanol: "caducar"},
{aleman: "das Nahrungsmittel", espanol: "el alimento"},
{aleman: "verteilen", espanol: "repartir"}
]
    },
   {
      id: 4,
      nombre: "leccion 4",
      palabras: [
{aleman: "nicht gut drauf sein", espanol: "estar de mal humor"},
{aleman: "der Konflikt", espanol: "el conflicto"},
{aleman: "der Eindruck", espanol: "la impresión"},
{aleman: "wütend", espanol: "furioso/a"},
{aleman: "erleichtert", espanol: "aliviado/a"},
{aleman: "stolz", espanol: "orgulloso/a"},
{aleman: "ängstlich", espanol: "miedoso/a"},
{aleman: "überraschen", espanol: "sorprender"},
{aleman: "die Überraschung", espanol: "la sorpresa"},
{aleman: "der Führerschein", espanol: "el carné de conducir"},
{aleman: "der Kletterpark", espanol: "el parque de escalada"},
{aleman: "das Tor", espanol: "el gol, la portería"},
{aleman: "schießen", espanol: "disparar, tirar"},
{aleman: "ausmachen", espanol: "apagar"},
{aleman: "Herzlichen Glückwunsch!", espanol: "¡Muchas felicidades!"},
{aleman: "enttäuschen", espanol: "decepcionar"},
{aleman: "die Laune", espanol: "el humor"},
{aleman: "der Nerv", espanol: "el nervio"},
{aleman: "die Beziehung", espanol: "la relación"},
{aleman: "musikalisch sein", espanol: "tener talento musical"},
{aleman: "extrem", espanol: "extremadamente"},
{aleman: "derselbe, dieselbe, dasselbe", espanol: "el mismo, la misma, lo mismo"},
{aleman: "prima", espanol: "estupendo/a"},
{aleman: "die Urkunde", espanol: "el documento"},
{aleman: "unglaublich", espanol: "increíble"},
{aleman: "die Kindheit", espanol: "la infancia"},
{aleman: "umgekehrt", espanol: "al revés"},
{aleman: "missverstehen", espanol: "entender mal"},
{aleman: "miteinander", espanol: "juntos/as"},
{aleman: "das Geheimnis", espanol: "el secreto"},
{aleman: "der Humor", espanol: "el humor"},
{aleman: "sich verlassen auf", espanol: "confiar en"},
{aleman: "einzigartig", espanol: "único/a"},
{aleman: "die Sorge", espanol: "la preocupación"},
{aleman: "kürzlich", espanol: "recientemente"},
{aleman: "ewig", espanol: "eternamente"},
{aleman: "violett", espanol: "violeta"},
{aleman: "quer durch", espanol: "a través de"},
{aleman: "voneinander", espanol: "el uno del otro"},
{aleman: "sich verlieben", espanol: "enamorarse"},
{aleman: "einsam", espanol: "solo/a"},
{aleman: "der Anruf", espanol: "la llamada"},
{aleman: "die Unterhaltung", espanol: "el entretenimiento"},
{aleman: "feststellen", espanol: "comprobar"},
{aleman: "sich irren", espanol: "equivocarse"},
{aleman: "der Idiot", espanol: "el idiota"},
{aleman: "die Idiotin", espanol: "la idiota"},
{aleman: "die Umfrage", espanol: "la encuesta"},
{aleman: "die Diskussion", espanol: "la discusión"},
{aleman: "das Sportcamp", espanol: "el campamento deportivo"},
{aleman: "das Ferienlager", espanol: "el campamento"},
{aleman: "verwenden", espanol: "usar"},
{aleman: "beachten", espanol: "atender"},
{aleman: "die Aufforderung", espanol: "el requerimiento"},
{aleman: "lächeln", espanol: "sonreír"},
{aleman: "die Absicht", espanol: "la intención"},
{aleman: "spinnen", espanol: "hilar"},
{aleman: "runterwerfen", espanol: "tirar"},
{aleman: "anschreien", espanol: "gritar a alguien"},
{aleman: "motzen", espanol: "refunfunar"},
{aleman: "die Rolle", espanol: "el papel"},
{aleman: "zerreißen", espanol: "rasgar"},
{aleman: "der Vorwurf", espanol: "el reproche"},
{aleman: "reagieren", espanol: "reaccionar"},
{aleman: "einlenken", espanol: "ceder"},
{aleman: "schuld sein", espanol: "ser culpable"},
{aleman: "die Schuld", espanol: "la culpa"},
{aleman: "sich beruhigen", espanol: "tranquilizarse"},
{aleman: "übertreiben", espanol: "exagerar"},
{aleman: "Verzeihung!", espanol: "¡Perdón!"},
{aleman: "Norwegen", espanol: "Noruega"},
{aleman: "überhaupt", espanol: "en general"},
{aleman: "behandeln", espanol: "tratar"},
{aleman: "die Ausrede", espanol: "la excusa"},
{aleman: "gemein", espanol: "malo/a"},
{aleman: "ob", espanol: "si"},
{aleman: "verletzen", espanol: "herir"},
{aleman: "neulich", espanol: "recientemente"},
{aleman: "heimlich", espanol: "en secreto"},
{aleman: "hassen", espanol: "odiar"},
{aleman: "die Art", espanol: "el modo"},
{aleman: "wahnsinnig", espanol: "tremendo/a"},
{aleman: "beleidigen", espanol: "ofender"},
{aleman: "das Ende", espanol: "el final"},
{aleman: "verzeihen", espanol: "perdonar"},
{aleman: "vertrauen", espanol: "confiar"},
{aleman: "das Gewissen", espanol: "la conciencia"},
{aleman: "erlaubt sein", espanol: "estar permitido/a"},
{aleman: "möglicherweise", espanol: "posiblemente"},
{aleman: "eifersüchtig", espanol: "celoso/a"},
{aleman: "so viel Zeit", espanol: "tanto tiempo"},
{aleman: "merkwürdig", espanol: "raro/a"},
{aleman: "sich mit jemandem verabreden", espanol: "quedar con alguien"},
{aleman: "vorschlagen", espanol: "proponer"},
{aleman: "bereit", espanol: "preparado/a"},
{aleman: "zusagen", espanol: "confirmar"},
{aleman: "nach Hause", espanol: "a casa"},
{aleman: "tauchen", espanol: "bucear"},
{aleman: "sich verhalten", espanol: "comportarse"},
{aleman: "der Ratgeber", espanol: "el consejero"}
]
    },
    {
      id: 5,
      nombre: "leccion 5",
      palabras: [
{aleman: "der Campingplatz", espanol: "el camping"},
{aleman: "die Umgebung", espanol: "los alrededores"},
{aleman: "der Service", espanol: "el servicio"},
{aleman: "entdecken", espanol: "descubrir"},
{aleman: "inklusive", espanol: "incluido/a"},
{aleman: "der Rekord", espanol: "el récord"},
{aleman: "die Million", espanol: "el millón"},
{aleman: "der Passagier", espanol: "el pasajero"},
{aleman: "die Passagierin", espanol: "la pasajera"},
{aleman: "der Flug", espanol: "el vuelo"},
{aleman: "der Beginn", espanol: "el comienzo"},
{aleman: "die Wartenschlange", espanol: "la cola de espera"},
{aleman: "das Terminal", espanol: "la terminal"},
{aleman: "der Schalter", espanol: "la ventanilla"},
{aleman: "das Bundesland", espanol: "el estado federado"},
{aleman: "der Stau", espanol: "el atasco"},
{aleman: "die Autobahn", espanol: "la autopista"},
{aleman: "die Strecke", espanol: "el trayecto"},
{aleman: "entlang", espanol: "a lo largo de"},
{aleman: "bis zu", espanol: "hasta"},
{aleman: "die Richtung", espanol: "la dirección"},
{aleman: "die Abfahrt", espanol: "la salida"},
{aleman: "das Gleis", espanol: "la vía"},
{aleman: "der Bahnsteig", espanol: "el andén"},
{aleman: "technisch", espanol: "técnico/a"},
{aleman: "die Störung", espanol: "la molestia"},
{aleman: "solch ein", espanol: "tal, semejante"},
{aleman: "möglichst", espanol: "si es posible"},
{aleman: "die Übernachtung", espanol: "la pernoctación"},
{aleman: "das Apartment", espanol: "el apartamento"},
{aleman: "die Durchsage", espanol: "el aviso"},
{aleman: "ausfallen", espanol: "cancelarse"},
{aleman: "der Lift", espanol: "el ascensor"},
{aleman: "der Eingang", espanol: "la entrada"},
{aleman: "der Ausgang", espanol: "la salida"},
{aleman: "das Obergeschoss", espanol: "la planta alta"},
{aleman: "das Untergeschoss", espanol: "el sótano"},
{aleman: "der Wintersportartikel", espanol: "el artículo de deportes de invierno"},
{aleman: "das Sonderangebot", espanol: "la oferta especial"},
{aleman: "landen", espanol: "aterrizar"},
{aleman: "die Landung", espanol: "el aterrizaje"},
{aleman: "einschalten", espanol: "encender"},
{aleman: "sich anschnallen", espanol: "ponerse el cinturón"},
{aleman: "der Autofahrer", espanol: "el conductor de coche"},
{aleman: "die Autofahrerin", espanol: "la conductora de coche"},
{aleman: "die Baustelle", espanol: "la obra"},
{aleman: "der Bereich", espanol: "el ámbito"},
{aleman: "die Geschwindigkeit", espanol: "la velocidad"},
{aleman: "der Preis", espanol: "el precio"},
{aleman: "die Teilnahme", espanol: "la participación"},
{aleman: "erfahren", espanol: "enterarse"},
{aleman: "anstrengend", espanol: "agotador/a"},
{aleman: "überreden", espanol: "convencer"},
{aleman: "vorhaben", espanol: "tener planeado"},
{aleman: "das/der Event", espanol: "el evento"},
{aleman: "das Souvenir", espanol: "el souvenir"},
{aleman: "der Traumurlaub", espanol: "las vacaciones de ensueño"},
{aleman: "die Realität", espanol: "la realidad"},
{aleman: "Chile", espanol: "Chile"},
{aleman: "Schottland", espanol: "Escocia"},
{aleman: "die Fähre", espanol: "el ferry"},
{aleman: "der Vampir", espanol: "el vampiro"},
{aleman: "erschrecken", espanol: "dar un susto"},
{aleman: "faulenzen", espanol: "vaguear"},
{aleman: "der Swimmingpool", espanol: "la piscina"},
{aleman: "der Ozean", espanol: "el océano"},
{aleman: "der Jahrmarkt", espanol: "la feria"},
{aleman: "zelten", espanol: "acampar"},
{aleman: "die Burg", espanol: "el castillo"},
{aleman: "sich verlaufen", espanol: "perderse"},
{aleman: "die Radtour", espanol: "la excursión en bici"},
{aleman: "die Beschränkung", espanol: "la restricción"},
{aleman: "überholen", espanol: "adelantar"},
{aleman: "der Halt", espanol: "la parada"},
{aleman: "der Nächste", espanol: "el siguiente"},
{aleman: "der Treffpunkt", espanol: "el punto de encuentro"},
{aleman: "der Akku", espanol: "la batería"},
{aleman: "aufladen", espanol: "cargar"},
{aleman: "die Panne", espanol: "la avería"},
{aleman: "der Gehsteig", espanol: "la acera"},
{aleman: "die Beschreibung", espanol: "la descripción"},
{aleman: "der Stadtplan", espanol: "el plano de la ciudad"},
{aleman: "gegenüber", espanol: "enfrente de"},
{aleman: "um herum", espanol: "alrededor de"},
{aleman: "breit", espanol: "ancho/a"},
{aleman: "der, das, die erste", espanol: "el/lo/la primero/a"},
{aleman: "die Kurve", espanol: "la curva"},
{aleman: "die Einbahnstraße", espanol: "la calle de sentido único"},
{aleman: "der Hauptbahnhof", espanol: "la estación central"},
{aleman: "überqueren", espanol: "Cruzar"},
{aleman: "abbiegen", espanol: "girar"},
{aleman: "daneben", espanol: "al lado"},
{aleman: "sich befinden", espanol: "encontrarse"},
{aleman: "der Zweck", espanol: "el objetivo"},
{aleman: "per", espanol: "por"},
{aleman: "das Abenteuer", espanol: "la aventura"},
{aleman: "zu Fuß", espanol: "a pie"},
{aleman: "das Boot", espanol: "el barco"},
{aleman: "maximal", espanol: "máximo/a"},
{aleman: "die Entfernung", espanol: "la distancia"},
{aleman: "zurücklegen", espanol: "recorrer"},
{aleman: "der Sponsor", espanol: "el patrocinador"},
{aleman: "spenden", espanol: "donar"},
{aleman: "die Spende", espanol: "la donación"},
{aleman: "der Betrag", espanol: "el importe"},
{aleman: "beschließen", espanol: "decidir"},
{aleman: "starten", espanol: "empezar"}
]
    },
{
      id: 6,
      nombre: "leccion 6 ",
      palabras:[
{aleman: "die Wissenschaft", espanol: "la ciencia"},
{aleman: "die Anlage", espanol: "el anexo"},
{aleman: "die Klimaanlage", espanol: "el aire acondicionado"},
{aleman: "der Staub", espanol: "el polvo"},
{aleman: "kommunizieren", espanol: "comunicar"},
{aleman: "passend", espanol: "adecuado/a"},
{aleman: "die Technologie", espanol: "la tecnologia"},
{aleman: "die Jugend", espanol: "la juventud"},
{aleman: "forschen", espanol: "investigar"},
{aleman: "speziell", espanol: "especial"},
{aleman: "anschliessen", espanol: "conectar"},
{aleman: "erfinden", espanol: "inventar"},
{aleman: "die Erfindung", espanol: "el invento"},
{aleman: "jederzeit", espanol: "en cualquier momento"},
{aleman: "blind", espanol: "ciego/a"},
{aleman: "unpraktisch", espanol: "poco practico"},
{aleman: "der Alarm", espanol: "la alarma"},
{aleman: "entwickeln", espanol: "desarrollar"},
{aleman: "warnen", espanol: "advertir"},
{aleman: "automatisch", espanol: "automatico/a"},
{aleman: "das Signal", espanol: "la senal"},
{aleman: "die Software", espanol: "el software"},
{aleman: "das Saarland", espanol: "el Sarre"},
{aleman: "der Unternehmer", espanol: "el empresario"},
{aleman: "die Unternehmerin", espanol: "la empresaria"},
{aleman: "mobil", espanol: "movil"},
{aleman: "die Bremse", espanol: "el freno"},
{aleman: "das Teil", espanol: "la parte"},
{aleman: "der Wahnsinn", espanol: "la locura"},
{aleman: "zurueckbringen", espanol: "devolver"},
{aleman: "die Datei", espanol: "el archivo"},
{aleman: "zeichnen", espanol: "dibujar"},
{aleman: "die Abgase", espanol: "los gases residuales"},
{aleman: "die Batterie", espanol: "la pila"},
{aleman: "die Bedeutung", espanol: "el significado"},
{aleman: "das Benzin", espanol: "la gasolina"},
{aleman: "der Diesel", espanol: "el diesel"},
{aleman: "das E-Bike", espanol: "la bicicleta electrica"},
{aleman: "elektrisch", espanol: "electrico/a"},
{aleman: "Elektro-", espanol: "electronico"},
{aleman: "die Energie", espanol: "la energia"},
{aleman: "die Station", espanol: "la estacion"},
{aleman: "die Steckdose", espanol: "el enchufe"},
{aleman: "tanken", espanol: "repostar"},
{aleman: "die Tankstelle", espanol: "la gasolinera"},
{aleman: "umweltfreundlich", espanol: "ecologico/a"},
{aleman: "sondern", espanol: "sino que"},
{aleman: "die Mobilitaet", espanol: "la movilidad"},
{aleman: "die Meldung", espanol: "el mensaje"},
{aleman: "die USA", espanol: "los EEUU"},
{aleman: "die Sensation", espanol: "la sensacion"},
{aleman: "die Medizin", espanol: "la medicina"},
{aleman: "das Gehirn", espanol: "el cerebro"},
{aleman: "ersetzen", espanol: "sustituir"},
{aleman: "die Entdeckung", espanol: "el descubrimiento"},
{aleman: "die Pflanze", espanol: "la planta"},
{aleman: "der Mond", espanol: "la luna"},
{aleman: "mieten", espanol: "alquilar"},
{aleman: "wundern", espanol: "asombrar"},
{aleman: "der Roboter", espanol: "el robot"},
{aleman: "einsetzen", espanol: "colocar"},
{aleman: "die Forschung", espanol: "la investigacion"},
{aleman: "intensiv", espanol: "intenso/a"},
{aleman: "die Wirklichkeit", espanol: "la realidad"},
{aleman: "selbststaendig", espanol: "autonomo/a"},
{aleman: "programmieren", espanol: "programar"},
{aleman: "benoetigen", espanol: "necesitar"},
{aleman: "allerdings", espanol: "sin embargo"},
{aleman: "das Verhalten", espanol: "el comportamiento"},
{aleman: "privat", espanol: "privado/a"},
{aleman: "das Gras", espanol: "la hierba"},
{aleman: "angenehm", espanol: "agradable"},
{aleman: "wischen", espanol: "limpiar"},
{aleman: "das Altenheim", espanol: "la residencia de mayores"},
{aleman: "begegnen", espanol: "encontrarse"},
{aleman: "die Bewegung", espanol: "el movimiento"},
{aleman: "ungefaehr", espanol: "aproximadamente"},
{aleman: "der Patient", espanol: "el paciente"},
{aleman: "die Patientin", espanol: "la paciente"},
{aleman: "einnehmen", espanol: "tomar un medicamento"},
{aleman: "unheimlich", espanol: "siniestro/a"},
{aleman: "erleichtern", espanol: "facilitar"},
{aleman: "der Kranke", espanol: "el enfermo"},
{aleman: "isoliert", espanol: "aislado/a"},
{aleman: "zu Hause", espanol: "en casa"},
{aleman: "die Beschaeftigung", espanol: "la ocupacion"},
{aleman: "die Industrie", espanol: "la industria"},
{aleman: "monoton", espanol: "monotono/a"},
{aleman: "die Produktion", espanol: "la produccion"},
{aleman: "der Betrieb", espanol: "la empresa"},
{aleman: "menschlich", espanol: "humano/a"},
{aleman: "der Arbeiter", espanol: "el trabajador"},
{aleman: "die Arbeiterin", espanol: "la trabajadora"},
{aleman: "der Angestellte", espanol: "el empleado"},
{aleman: "verschwinden", espanol: "desaparecer"},
{aleman: "der Arbeitsplatz", espanol: "el puesto de trabajo"},
{aleman: "der Abschnitt", espanol: "el parrafo"},
{aleman: "die Einleitung", espanol: "la introduccion"},
{aleman: "springen", espanol: "saltar"},
{aleman: "loesen", espanol: "resolver"},
{aleman: "der Badeanzug", espanol: "el banador"},
{aleman: "die Badehose", espanol: "el banador"},
{aleman: "alternativ", espanol: "alternativo/a"},
{aleman: "verbrauchen", espanol: "consumir"},
{aleman: "wegen", espanol: "a causa de"},
{aleman: "zahlreich", espanol: "numeroso/a"},
{aleman: "nachdenken", espanol: "reflexionar"},
{aleman: "handeln", espanol: "actuar"},
{aleman: "das Klima", espanol: "el clima"},
{aleman: "der Klimawandel", espanol: "el cambio climatico"},
{aleman: "verschwenden", espanol: "derrochar"},
{aleman: "die Luft", espanol: "el aire"},
{aleman: "das Plastik", espanol: "el plastico"},
{aleman: "der Kunststoff", espanol: "el plastico"},
{aleman: "das Insekt", espanol: "el insecto"},
{aleman: "oeffentlich", espanol: "publico/a"},
{aleman: "kostenlos", espanol: "gratuito/a"},
{aleman: "der Umweltschutz", espanol: "la proteccion del medio ambiente"},
{aleman: "der Vortrag", espanol: "la conferencia"},
{aleman: "der Zuhoerer", espanol: "el oyente"},
{aleman: "die Zuhoererin", espanol: "la oyente"},
{aleman: "verstaendlich", espanol: "comprensible"},
{aleman: "die Praesentation", espanol: "la presentacion"},
{aleman: "die Folie", espanol: "el folio"},
{aleman: "der Inhalt", espanol: "el contenido"},
{aleman: "die Struktur", espanol: "la estructura"},
{aleman: "das Erlebnis", espanol: "la experiencia"},
{aleman: "der Zusammenhang", espanol: "el contexto"},
{aleman: "positiv", espanol: "positivo/a"},
{aleman: "negativ", espanol: "negativo/a"},
{aleman: "der Abschluss", espanol: "la conclusion"},
{aleman: "die Aufmerksamkeit", espanol: "la atencion"},
{aleman: "die Kommunikation", espanol: "la comunicacion"},
{aleman: "die Temperatur", espanol: "la temperatura"},
{aleman: "die Kranke", espanol: "la enferma"},
{aleman: "die Angestellte", espanol: "la empleada"}
]
    },
    {
      id: 7,
      nombre: "leccion 7 ",
      palabras:[
      
{
aleman: "der Stadtmusikant",espanol: "el músico "},
{aleman: "mit summen",espanol: "tararear una melodía"},
{aleman: "der Cartoon",espanol: "el dibujo, la caricatura"},
{aleman: "mailen",espanol: "enviar un correo electrónico"},
{aleman: "der Nerv",espanol: "el nervio"},
{aleman: "das Schulbuch, die Schulbücher",espanol: "el libro de texto"},
{aleman: "unangenehm",espanol: "desagradable"},
{aleman: "worüber",espanol: "sobre qué"},
{aleman: "langweilen (sich)",espanol: "aburrir(se)"},
{aleman: "der Schulabschluss, die Schulabschlüsse",espanol: "el diploma escolar"},
{aleman: "das Schulsystem",espanol: "el sistema escolar"},
{aleman: "der Umzug",espanol: "la mudanza"},
{aleman: "wissen, wusste, hat gewusst",espanol: "saber"},
{aleman: "ziehen, zog, ist gezogen ",espanol: " mudarse "},
{aleman: "der Anwalt, die Anwälte",espanol: "el abogado"},
{aleman: "die Anwältin, die Anwältinnen",espanol: "la abogada"},
{aleman: "ausreichen, reichte aus, hat ausgereicht",espanol: "ser suficiente"},
{aleman: "einheitlich",espanol: "uniforme"},
{aleman: "die Empfehlung, die Empfehlungen",espanol: "la recomendación"},
{aleman: "die Fachhochschule",espanol: "tipo de universidad en Alemania"},
{aleman: "der Fachinformatiker",espanol: "el informático"},
{aleman: "die Fachinformatikerin, die Fachinformatikerinnen",espanol: "la informática"},
{aleman: "die Gesamtschule",espanol: "la escuela integrada"},
{aleman: "die Grundschule",espanol: "el colegio de primaria"},
{aleman: "der Hauptschulabschluss, die Hauptschulabschlüsse",espanol: "el título de graduado"},
{aleman: "die Hauptschule",espanol: "la ESO"},
{aleman: "heißen, hieß, hat geheißen ",espanol: "llamarse, significar"},
{aleman: "die Lehre",espanol: "la formación profesional"},
{aleman: "der Lehrling, die Lehrlinge",espanol: "el aprendiz"},
{aleman: "machen ",espanol: "hacer "},
{aleman: "der Mechaniker",espanol: "el mecánico"},
{aleman: "die Mechanikerin, die Mechanikerinnen",espanol: "la mecánica"},
{aleman: "die Mittlere Reife",espanol: "la titulación de enseñanza media"},
{aleman: "der Realschulabschluss,die Realschulabschlüsse",espanol: "el título de enseñanza media"},
{aleman: "die Realschule",espanol: "el instituto de enseñanza media"},
{aleman: "die Voraussetzung, die Voraussetzungen",espanol: "el requisito"},
{aleman: "voraussichtlich",espanol: "previsiblemente"},
{aleman: "die Abbildung",espanol: "el dibujo"},
{aleman: "der Bachelor",espanol: " el título de grado"},
{aleman: "die Berufsausbildung",espanol: "la formación profesional"},
{aleman: "das Diplom",espanol: "el diploma"},
{aleman: "der Forumstext",espanol: "el texto en un foro"},
{aleman: "die Hochschule",espanol: "la universidad"},
{aleman: "der Master",espanol: "el master"},
{aleman: "die Radiosendung",espanol: "el programa de radio"},
{aleman: "heutzutage",espanol: "hoy en día"},
{aleman: "innerhalb von ",espanol: "en"},
{aleman: "der Klassenraum, die Klassenräume",espanol: "el aula"},
{aleman: "die Sprachreise",espanol: "el viaje para aprender un idioma"},
{aleman: "die Unterrichtszeit",espanol: "el horario de clase"},
{aleman: "weiter hören",espanol: "seguir escuchando"},
{aleman: "der Zeitraum, die Zeiträume",espanol: "el periodo de tiempo"},
{aleman: "die Schulnote",espanol: "la nota"},
{aleman: "ausreichend",espanol: "suficiente (nota)"},
{aleman: "befriedigend",espanol: "bien (nota)"},
{aleman: "die Klassenarbeit",espanol: "el examen"},
{aleman: "mangelhaft",espanol: "suspenso (nota)"},
{aleman: "ungenügend",espanol: "suspenso (nota)"},
{aleman: "anstehen, steht an, stand an, hat angestanden",espanol: "celebrarse pronto"},
{aleman: "Der nächste Test steht bald an",espanol: "Pronto tendremos el siguiente examen"},
{aleman: "ausgeruht",espanol: "descansado,descansada"},
{aleman: "sich bemühen um)",espanol: "esforzarse"},
{aleman: "der Druck",espanol: "la presión"},
{aleman: "durchlesen, las durch, hat durchgelesen",espanol: "leer"},
{aleman: "sich entspannen, sich entspannte, sich entspannt ",espanol: "relajarse"},
{aleman: "erfolgreich",espanol: "exitoso, exitosa"},
{aleman: "sich erholen von, sich erholte von, hat sich vonerholt.)",espanol: "descansar"},
{aleman: "die Erholung ",espanol: "el descanso"},
{aleman: "erschöpft",espanol: "agotado,agotada"},
{aleman: "fördern, förderte, hat gefördert",espanol: " fomentar"},
{aleman: "das Freizeitprogramm",espanol: "el programa de tiempo libre"},
{aleman: "hell",espanol: "luminoso"},
{aleman: "individuell",espanol: "individual"},
{aleman: "sich konzentrieren  auf",spanol: "concentrarse"},
{aleman: "die Lernzeit",espanol: "el tiempo de estudio"},
{aleman: "die Panik",espanol: "el pánico"},
{aleman: "rechtzeitig",espanol: "a tiempo"},
{aleman: "der Schulstress",espanol: "el estrés del estudiante escolar"},
{aleman: "spätestens",espanol: "a más tardar"},
{aleman: "der Spaziergang",espanol: "el paseo"},
{aleman: "übrigens",espanol: "por cierto"},
{aleman: "um gehen mit, ging um, ist umgegangen",espanol: "tratar"},
{aleman: "vermeiden, vermied, hat vermieden",espanol: "evitar"},
{aleman: "die Vorbereitung",espanol: "la preparación"},
{aleman: "die Vorbereitungszeit",espanol: "el período de preparación"},
{aleman: "wach",espanol: "despierto"},
{aleman: "während " ,espanol: "durante"},
{aleman: "Während der Pause bin ich wirklich entspannt",espanol: "En el descanso estoy muy relajado"},
{aleman: "der Zeitplan, die Zeitpläne",espanol: "la programación, el horario"},
{aleman: "der Notenstress",espanol: "el estrés por las notas"},
{aleman: "der Lerntipp, die Lerntipps",espanol: "el consejo para aprender mejor"},
{aleman: "aus",espanol: " de, por"},
{aleman: "von mir aus",espanol: "por mí sí"},
{aleman: "der Einfall, die Einfälle",espanol: "la idea, la ocurrencia"},
{aleman: "sich einigen auf ",espanol: "llegar a un acuerdo, ponerse de acuerdo"},
{aleman: "einverstanden sein mit ",espanol: "estar de acuerdo"},
{aleman: "der Gegenvorschlag, die Gegenvorschläge",espanol: "la contrapropuesta"},
{aleman: "meinetwegen",espanol: "por mi culpa"},
{aleman: "der Arbeitslohn, Arbeitslöhne",espanol: "el sueldo"},
{aleman: "die Arbeitsstelle, die Arbeitsstellen",espanol: "el puesto de trabajo"},
{aleman: "der Bauch",espanol: "el estómago "},
{aleman: "die Berufschance", espanol: "la oportunidad de trabajo"},
{aleman: "sich bewerben um bewarb, hat beworben",espanol: "solicitar trabajo,una beca"},
{aleman: "eher",espanol: "más bien"},
{aleman: "die Fähigkeit, die Fähigkeiten",espanol: "la capacidad"},
{aleman: "konkret",espanol: "en concreto"},
{aleman: "die Prozentzahl, -en",espanol: "el porcentaje"},
{aleman: "die Selbstverwirklichung",espanol: "el desarrollo personal"},
{aleman: "die Mehrheit ",espanol: "la mayoría de la gente"},
{aleman: "An erster Stelle",espanol: "En primer lugar"},
{aleman: "die Statistik, die Statistiken",espanol: "la estadística"},
{aleman: "das Einkommen",espanol: "los ingresos"},
{aleman: "erst mal",espanol: "lo primero que se hace"},
{aleman: "falls",espanol: "en caso de que"},
{aleman: "das Futur", espanol: "el futuro"},
{aleman: "das Präsens",espanol: "el presente"},
{aleman: "der Wortschatz",espanol: "el vocabulario"}
      ]
    },
      {
      id: 8,
      nombre: "leccion 8 ",
      palabras:[
{aleman: "der Zuschauer", espanol: "el espectador"},
{aleman: "die Zuschauerin", espanol: "la espectadora"},
{aleman: "begeistert", espanol: "entusiasmado/a"},
{aleman: "streiken", espanol: "hacer huelga"},
{aleman: "global", espanol: "a nivel internacional (global)"},
{aleman: "demonstrieren", espanol: "manifestarse"},
{aleman: "der Flüchtling", espanol: "el/la refugiado/a"},
{aleman: "das Asyl", espanol: "el asilo político"},
{aleman: "beantragen", espanol: "solicitar"},
{aleman: "der Bundeskanzler", espanol: "el canciller"},
{aleman: "die Bundeskanzlerin", espanol: "la canciller"},
{aleman: "die Spitze", espanol: "la cima"},
{aleman: "die Regierung", espanol: "el gobierno"},
{aleman: "der Sitz", espanol: "la sede"},
{aleman: "die Fußballweltmeisterschaft", espanol: "el mundial de fútbol"},
{aleman: "das Herz", espanol: "el corazón"},
{aleman: "der Weltmeister", espanol: "el campeón del mundo"},
{aleman: "das Ereignis", espanol: "el acontecimiento"},
{aleman: "die Geburt", espanol: "el nacimiento"},
{aleman: "der Weltkrieg", espanol: "la guerra mundial"},
{aleman: "die Bundesrepublik (Deutschland)", espanol: "la República Federal de Alemania"},
{aleman: "die DDR (Deutsche Demokratische Republik)", espanol: "la RDA (República Democrática Alemana)"},
{aleman: "geteilt", espanol: "dividido/a"},
{aleman: "demokratisch", espanol: "democrático/a"},
{aleman: "kritisieren", espanol: "criticar"},
{aleman: "offen", espanol: "abierto/a"},
{aleman: "verlassen", espanol: "abandonar"},
{aleman: "der Einwohner", espanol: "el habitante"},
{aleman: "die Einwohnerin", espanol: "la habitante"},
{aleman: "die Grenze", espanol: "la frontera"},
{aleman: "bewachen", espanol: "vigilar"},
{aleman: "flüchten", espanol: "huir"},
{aleman: "die Flucht", espanol: "la huida"},
{aleman: "die Freiheit", espanol: "la libertad"},
{aleman: "die Demonstration", espanol: "la manifestación"},
{aleman: "die Demo", espanol: "la manifestación (abreviación)"},
{aleman: "aufgeben", espanol: "rendirse"},
{aleman: "der Staat", espanol: "el estado"},
{aleman: "die Wiedervereinigung", espanol: "la reunificación"},
{aleman: "der Nationalfeiertag", espanol: "la fiesta nacional"},
{aleman: "die Stadtrundfahrt", espanol: "el recorrido por la ciudad"},
{aleman: "der Reiseführer", espanol: "el guía turístico"},
{aleman: "die Reiseführerin", espanol: "la guía turística"},
{aleman: "die Tour", espanol: "el recorrido"},
{aleman: "der Turm", espanol: "la torre"},
{aleman: "die Aussicht", espanol: "la vista"},
{aleman: "der Stopp", espanol: "la parada"},
{aleman: "das Gebäude", espanol: "el edificio"},
{aleman: "das Parlament", espanol: "el parlamento"},
{aleman: "das Denkmal", espanol: "el monumento"},
{aleman: "die Altstadt", espanol: "el casco antiguo"},
{aleman: "erleben", espanol: "vivir (experimentar)"},
{aleman: "die Metropole", espanol: "la metrópoli"},
{aleman: "historisch", espanol: "histórico/a"},
{aleman: "sich wohl fühlen", espanol: "estar a gusto"},
{aleman: "der Leser", espanol: "el lector"},
{aleman: "die Leserin", espanol: "la lectora"},
{aleman: "die Einsamkeit", espanol: "la soledad"},
{aleman: "der Ehrgeiz", espanol: "la ambición"},
{aleman: "die Laufbahn", espanol: "la carrera profesional"},
{aleman: "die Verantwortung", espanol: "la responsabilidad"},
{aleman: "das Vorbild", espanol: "el ejemplo (a seguir)"},
{aleman: "die Partnerschaft", espanol: "la relación (de pareja, la colaboración)"},
{aleman: "der Protest", espanol: "la protesta"},
{aleman: "die Neugierde", espanol: "la curiosidad"},
{aleman: "erwachsen", espanol: "adulto/a"},
{aleman: "losfahren", espanol: "arrancar (salir - en un vehículo)"},
{aleman: "Slowenien", espanol: "Eslovenia"},
{aleman: "Liechtenstein", espanol: "Liechtenstein"},
{aleman: "schüchtern", espanol: "tímido/a"},
{aleman: "die Enttäuschung", espanol: "la decepción"},
{aleman: "der Bekannte", espanol: "el conocido"},
{aleman: "die Bekannte", espanol: "la conocida"},
{aleman: "die Trennung", espanol: "la separación"},
{aleman: "sich trennen", espanol: "separarse"},
{aleman: "die Scheidung", espanol: "el divorcio"},
{aleman: "das Halbfinale", espanol: "la semifinal"},
{aleman: "sich anstrengen", espanol: "esforzarse"},
{aleman: "die Mühe", espanol: "el esfuerzo"},
{aleman: "stürzen", espanol: "caerse"},
{aleman: "die Verletzung", espanol: "la lesión"},
{aleman: "die Erinnerung", espanol: "el recuerdo"},
{aleman: "verantwortlich", espanol: "responsable"},
{aleman: "der Nachwuchs", espanol: "la nueva generación"},
{aleman: "die Atomkraft", espanol: "la energía nuclear"},
{aleman: "die Katastrophe", espanol: "el desastre"},
{aleman: "sich ereignen", espanol: "suceder"},
{aleman: "geschehen", espanol: "ocurrir"},
{aleman: "protestieren", espanol: "protestar"},
{aleman: "der Schock", espanol: "el shock"},
{aleman: "beinahe", espanol: "por poco"},
{aleman: "nebenbei", espanol: "al mismo tiempo (de paso)"},
{aleman: "der Kampf", espanol: "la lucha"},
{aleman: "die Umweltverschmutzung", espanol: "la contaminación"},
{aleman: "die Politik", espanol: "la política"},
{aleman: "ab und zu", espanol: "de vez en cuando"},
{aleman: "der Bildschirm", espanol: "la pantalla"},
{aleman: "der Augenblick", espanol: "el momento"},
{aleman: "das Semester", espanol: "el semestre"},
{aleman: "heiraten", espanol: "casarse"},
{aleman: "ideal", espanol: "idóneo/a"},
{aleman: "davor", espanol: "antes"},
{aleman: "bevor", espanol: "antes de"},
{aleman: "nachdem", espanol: "después de"},
{aleman: "während", espanol: "durante (mientras)"},
{aleman: "der Spiegel", espanol: "el espejo"},
{aleman: "schockiert", espanol: "horrorizado/a"},
{aleman: "frei bekommen", espanol: "tener libre (no tener que ir a clase, a trabajar)"},
{aleman: "hingehen", espanol: "ir (dirigirse a un sitio)"}
]
    },
         {
      id: 9,
      nombre: "leccion 9 ",
      palabras:[
{aleman: "trendy (trendig)", espanol: "de moda"},
{aleman: "die Fee", espanol: "el hada"},
{aleman: "der Flop", espanol: "el fracaso"},
{aleman: "wahr", espanol: "verdadero/a"},
{aleman: "tauschen", espanol: "intercambiar"},
{aleman: "umsonst", espanol: "gratis"},
{aleman: "das Prinzip", espanol: "el principio"},
{aleman: "wertvoll", espanol: "valioso/a"},
{aleman: "wertlos", espanol: "sin valor"},
{aleman: "sich verbreiten", espanol: "extenderse"},
{aleman: "der Schlüsselanhänger", espanol: "el llavero"},
{aleman: "hergeben", espanol: "entregar (dar)"},
{aleman: "entschlossen", espanol: "decidido/a"},
{aleman: "bis", espanol: "hasta"},
{aleman: "fortsetzen", espanol: "continuar"},
{aleman: "simpel", espanol: "sencillo/a"},
{aleman: "finanziell", espanol: "económicamente"},
{aleman: "sich etwas leisten können", espanol: "poder permitirse algo"},
{aleman: "das Mitglied", espanol: "el miembro"},
{aleman: "das Zeitkonto", espanol: "el banco de tiempo"},
{aleman: "die Nachbarschaft", espanol: "el barrio (vecindario)"},
{aleman: "der Haarschnitt", espanol: "el corte de pelo"},
{aleman: "gratis", espanol: "gratis"},
{aleman: "der Gegenstand", espanol: "el objeto"},
{aleman: "der Profi", espanol: "el profesional"},
{aleman: "kaputtgehen", espanol: "estropearse"},
{aleman: "umsetzen", espanol: "llevar a cabo"},
{aleman: "brauchen", espanol: "necesitar"},
{aleman: "das Schulkonzert", espanol: "el concierto escolar"},
{aleman: "das Vokabelheft", espanol: "el cuaderno de vocabulario"},
{aleman: "lebendig", espanol: "vivo/a"},
{aleman: "überzeugen", espanol: "convencer"},
{aleman: "die Stelle", espanol: "el lugar"},
{aleman: "der Pass", espanol: "el pasaporte"},
{aleman: "das Girokonto", espanol: "la cuenta corriente"},
{aleman: "die Bankkarte", espanol: "la tarjeta bancaria"},
{aleman: "die EC-Karte", espanol: "la tarjeta de débito"},
{aleman: "die PIN (-Nummer)", espanol: "el pin"},
{aleman: "zuschicken", espanol: "enviar"},
{aleman: "der Automat", espanol: "la máquina"},
{aleman: "der Geldautomat", espanol: "el cajero automático"},
{aleman: "das Bargeld", espanol: "el dinero en efectivo"},
{aleman: "bar zahlen", espanol: "pagar en efectivo"},
{aleman: "abheben", espanol: "retirar (dinero)"},
{aleman: "auszahlen", espanol: "sacar (dinero)"},
{aleman: "einzahlen", espanol: "ingresar (dinero)"},
{aleman: "das Jahrhundert", espanol: "el siglo"},
{aleman: "die Münze", espanol: "la moneda"},
{aleman: "herstellen", espanol: "fabricar"},
{aleman: "Indien", espanol: "la India"},
{aleman: "der Schein", espanol: "el billete"},
{aleman: "die Deutsche Mark", espanol: "el marco alemán (antigua moneda de Alemania Occidental)"},
{aleman: "einführen", espanol: "implantar (introducir)"},
{aleman: "überwachen", espanol: "vigilar"},
{aleman: "sich auskennen", espanol: "conocer bien"},
{aleman: "der Stein", espanol: "la piedra"},
{aleman: "das Gold", espanol: "el oro"},
{aleman: "die Ware", espanol: "la mercancía"},
{aleman: "handeln", espanol: "comerciar"},
{aleman: "das Recht", espanol: "el derecho"},
{aleman: "die Pflicht", espanol: "el deber"},
{aleman: "verpflichten", espanol: "obligar"},
{aleman: "die Reklamation", espanol: "la reclamación"},
{aleman: "reklamieren", espanol: "reclamar"},
{aleman: "(an)statt (zu)", espanol: "en vez de"},
{aleman: "behalten", espanol: "quedarse con"},
{aleman: "der Verkäufer", espanol: "el vendedor"},
{aleman: "die Verkäuferin", espanol: "la vendedora"},
{aleman: "der Käufer", espanol: "el comprador"},
{aleman: "die Käuferin", espanol: "la compradora"},
{aleman: "der Kauf", espanol: "la compra"},
{aleman: "nämlich", espanol: "es decir"},
{aleman: "umtauschen", espanol: "cambiar (por otra cosa, devolver)"},
{aleman: "freiwillig", espanol: "voluntario/a"},
{aleman: "die Summe", espanol: "la suma"},
{aleman: "verlangen", espanol: "exigir"},
{aleman: "beweisen", espanol: "demostrar (probar)"},
{aleman: "die Quittung", espanol: "el recibo"},
{aleman: "der Beleg", espanol: "el comprobante"},
{aleman: "der Zeuge", espanol: "el testigo"},
{aleman: "vorkommen", espanol: "pasar (ocurrir)"},
{aleman: "die Alternative", espanol: "la alternativa"},
{aleman: "die Qualität", espanol: "la calidad"},
{aleman: "die Garantie", espanol: "la garantía"},
{aleman: "ärgerlich", espanol: "molesto/a (irritante)"},
{aleman: "die Lautstärke", espanol: "el volumen"},
{aleman: "einstellen", espanol: "ajustar"},
{aleman: "selbstverständlich", espanol: "por supuesto"},
{aleman: "das Loch", espanol: "el agujero"},
{aleman: "der Fleck", espanol: "la mancha"},
{aleman: "die Powerbank", espanol: "la batería externa (para el móvil)"},
{aleman: "das Kabel", espanol: "el cable"},
{aleman: "testen", espanol: "probar"},
{aleman: "der Skaterpark", espanol: "el parque de patinaje"},
{aleman: "die Währung", espanol: "la moneda (la divisa)"},
{aleman: "der Konsum", espanol: "el consumo"}
]
    },
           {
      id: 10,
      nombre: "leccion 10",
      palabras: [
{aleman: "die Menge", espanol: "la cantidad"},
{aleman: "eine Menge Arbeit", espanol: "mucho trabajo"},
{aleman: "die Szene", espanol: "la escena (la situación)"},
{aleman: "der Fahrlehrer", espanol: "el profesor de autoescuela"},
{aleman: "die Fahrlehrerin", espanol: "la profesora de autoescuela"},
{aleman: "der Flugbegleiter", espanol: "el auxiliar de vuelo"},
{aleman: "die Flugbegleiterin", espanol: "la auxiliar de vuelo"},
{aleman: "der Steward", espanol: "el auxiliar de vuelo"},
{aleman: "die Stewardess", espanol: "la auxiliar de vuelo"},
{aleman: "der Maler", espanol: "el pintor"},
{aleman: "die Malerin", espanol: "la pintora"},
{aleman: "der Richter", espanol: "el juez"},
{aleman: "die Richterin", espanol: "la juez(a)"},
{aleman: "die Krankenschwester", espanol: "la enfermera"},
{aleman: "der Krankenpfleger", espanol: "el enfermero"},
{aleman: "die Eigenschaft", espanol: "la característica"},
{aleman: "die Auswahl", espanol: "la selección"},
{aleman: "geduldig", espanol: "paciente"},
{aleman: "engagiert", espanol: "comprometido/a"},
{aleman: "zuverlässig", espanol: "de confianza"},
{aleman: "fleißig", espanol: "trabajador/a"},
{aleman: "der Vorteil", espanol: "la ventaja"},
{aleman: "der Nachteil", espanol: "el inconveniente"},
{aleman: "die Bedingung", espanol: "la condición"},
{aleman: "gut bezahlt", espanol: "bien pagado/a"},
{aleman: "stressig", espanol: "estresante"},
{aleman: "anstrengend", espanol: "agotador/a"},
{aleman: "die Unterlagen", espanol: "la documentación"},
{aleman: "der Lebenslauf", espanol: "el currículum vitae"},
{aleman: "das Zeugnis", espanol: "el certificado"},
{aleman: "die Bewerbung", espanol: "la solicitud (la candidatura)"},
{aleman: "sich bewerben", espanol: "solicitar un trabajo (presentar la candidatura)"},
{aleman: "die Anzeige", espanol: "el anuncio"},
{aleman: "das Ergebnis", espanol: "el resultado"},
{aleman: "der Arbeitgeber", espanol: "el/la empresario/a"},
{aleman: "die Arbeitgeberin", espanol: "la empresaria"},
{aleman: "der Arbeitnehmer", espanol: "el empleado"},
{aleman: "die Arbeitnehmerin", espanol: "la empleada"},
{aleman: "der Arbeitsmarkt", espanol: "el mercado laboral"},
{aleman: "das Praktikum", espanol: "las prácticas"},
{aleman: "die Stelle", espanol: "el puesto de trabajo"},
{aleman: "die Arbeitszeit", espanol: "la jornada laboral"},
{aleman: "suchen", espanol: "buscar"},
{aleman: "die Suche", espanol: "la búsqueda"},
{aleman: "erfolgreich", espanol: "con éxito"},
{aleman: "wichtig", espanol: "importante"},
{aleman: "die Agentur", espanol: "la agencia"},
{aleman: "die Bewerbungsmappe", espanol: "el portfolio de solicitud"},
{aleman: "das Porträtfoto", espanol: "la foto de carné"},
{aleman: "unterschreiben", espanol: "firmar"},
{aleman: "die Unterschrift", espanol: "la firma"},
{aleman: "vollständig", espanol: "completo/a"},
{aleman: "fehlen", espanol: "faltar"},
{aleman: "der Betreff", espanol: "el asunto (el tema)"},
{aleman: "die Anrede", espanol: "el saludo"},
{aleman: "die Grußformel", espanol: "el saludo de despedida"},
{aleman: "die Schulbildung", espanol: "la formación escolar"},
{aleman: "die Schulzeit", espanol: "la etapa escolar"},
{aleman: "die Fremdsprache", espanol: "la lengua extranjera"},
{aleman: "der Abschnitt", espanol: "la sección"},
{aleman: "der Abschluss", espanol: "el fin (el final)"},
{aleman: "unterscheiden", espanol: "diferenciar"},
{aleman: "sich unterscheiden", espanol: "diferenciarse"},
{aleman: "der Buchstabe", espanol: "la letra"},
{aleman: "die Zahl", espanol: "el número"},
{aleman: "der Text", espanol: "el texto"},
{aleman: "das Foto", espanol: "la foto"},
{aleman: "das Papier", espanol: "el papel"},
{aleman: "das Gespräch", espanol: "la conversación"},
{aleman: "die Besprechung", espanol: "la reunión"},
{aleman: "die Unterhaltung", espanol: "el entretenimiento"},
{aleman: "verbessern", espanol: "mejorar"},
{aleman: "das Trinkgeld", espanol: "la propina"},
{aleman: "mitteilen", espanol: "informar"},
{aleman: "ebenso", espanol: "igualmente"},
{aleman: "der Fotograf", espanol: "el fotógrafo"},
{aleman: "der Elefant", espanol: "el elefante"},
{aleman: "füttern", espanol: "dar de comer"},
{aleman: "der Punkt", espanol: "el punto"},
{aleman: "der Betreff", espanol: "el asunto"},
{aleman: "der Empfänger", espanol: "el destinatario"},
{aleman: "die Motivation", espanol: "la motivación"},
{aleman: "der Absender", espanol: "el remitente"},
{aleman: "die Anrede", espanol: "el encabezamiento"},
{aleman: "geehrter", espanol: "estimado"},
{aleman: "geehrte", espanol: "estimada"},
{aleman: "die Dame", espanol: "la señora"},
{aleman: "zurzeit", espanol: "actualmente"},
{aleman: "das Vorstellungsgespräch", espanol: "la entrevista de trabajo"},
{aleman: "Mit freundlichen Grüßen", espanol: "saludos cordiales"},
{aleman: "die Anlage", espanol: "el adjunto"},
{aleman: "gliedern", espanol: "estructurar"}
]
    },
             {
      id: 11,
      nombre: "leccion 11 ",
      palabras: [
{aleman: "der Bundestag", espanol: "el Parlamento Federal (Alemania)"},
{aleman: "politisch", espanol: "político/a"},
{aleman: "das Amt", espanol: "el cargo"},
{aleman: "der Bürger", espanol: "el ciudadano"},
{aleman: "die Bürgerin", espanol: "la ciudadana"},
{aleman: "repräsentieren", espanol: "representar"},
{aleman: "die Partei", espanol: "el partido"},
{aleman: "der Minister", espanol: "el ministro"},
{aleman: "die Ministerin", espanol: "la ministra"},
{aleman: "die EU", espanol: "la UE"},
{aleman: "die Union", espanol: "la unión"},
{aleman: "europäisch", espanol: "europeo/a"},
{aleman: "die Politikerin", espanol: "la política (persona)"},
{aleman: "der Politiker", espanol: "el político (persona)"},
{aleman: "der Bundespräsident", espanol: "el Presidente Federal (Alemania)"},
{aleman: "die Bundespräsidentin", espanol: "la Presidenta Federal (Alemania)"},
{aleman: "der Präsident", espanol: "el presidente"},
{aleman: "die Präsidentin", espanol: "la presidenta"},
{aleman: "der Kanzler", espanol: "el canciller"},
{aleman: "die Kanzlerin", espanol: "la canciller"},
{aleman: "die Erklärung", espanol: "la explicación (la declaración)"},
{aleman: "das Puzzle", espanol: "el puzle"},
{aleman: "zusammengehören", espanol: "ir junto (pertenecer)"},
{aleman: "sich engagieren", espanol: "comprometerse"},
{aleman: "damit", espanol: "para que"},
{aleman: "abstimmen", espanol: "votar"},
{aleman: "die Gratulation", espanol: "la felicitación"},
{aleman: "der Bürgermeister", espanol: "el alcalde"},
{aleman: "die Bürgermeisterin", espanol: "la alcaldesa"},
{aleman: "der Radfahrer", espanol: "el ciclista"},
{aleman: "die Radfahrerin", espanol: "la ciclista"},
{aleman: "hinweisen", espanol: "indicar"},
{aleman: "die Umweltgruppe", espanol: "la asociación ecologista"},
{aleman: "der Klimaschutz", espanol: "la protección del clima"},
{aleman: "erneuerbare Energien", espanol: "las energías renovables"},
{aleman: "die Umwelt", espanol: "el medio ambiente"},
{aleman: "fair", espanol: "justo/a"},
{aleman: "das Umweltbewusstsein", espanol: "la conciencia medioambiental"},
{aleman: "der Verein", espanol: "la asociación"},
{aleman: "der Bürgerentscheid", espanol: "la consulta popular (el referéndum)"},
{aleman: "das Rathaus", espanol: "el ayuntamiento"},
{aleman: "abstimmen über", espanol: "votar sobre"},
{aleman: "sich kümmern um", espanol: "ocuparse de"},
{aleman: "gründen", espanol: "fundar"},
{aleman: "die Zukunft", espanol: "el futuro"},
{aleman: "aktiv", espanol: "activo/a"},
{aleman: "schonend", espanol: "suave (delicado/a)"},
{aleman: "die Öffentlichkeit", espanol: "el público"},
{aleman: "das Engagement", espanol: "la implicación"},
{aleman: "der Kindergarten", espanol: "el jardín de infancia"},
{aleman: "der Stadtteil", espanol: "el barrio"},
{aleman: "die Anlage", espanol: "la instalación"},
{aleman: "der Stadtrat", espanol: "el concejal"},
{aleman: "die Stadträtin", espanol: "la concejala"},
{aleman: "der/die Jugendliche", espanol: "el/la joven"},
{aleman: "ernst nehmen", espanol: "tomar en serio"},
{aleman: "die Meinung", espanol: "la opinión"},
{aleman: "der Mut", espanol: "el valor"},
{aleman: "mutig", espanol: "valiente"},
{aleman: "das Selbstvertrauen", espanol: "la confianza en sí mismo"},
{aleman: "selbstbewusst", espanol: "seguro de sí mismo"},
{aleman: "loben", espanol: "elogiar"},
{aleman: "der Betreuer", espanol: "el cuidador"},
{aleman: "die Betreuerin", espanol: "la cuidadora"},
{aleman: "der Sozialarbeiter", espanol: "el trabajador social"},
{aleman: "die Sozialarbeiterin", espanol: "la trabajadora social"},
{aleman: "einfallen", espanol: "ocurrir"},
{aleman: "die Gesellschaft", espanol: "la sociedad"},
{aleman: "sogenannt", espanol: "así llamado"},
{aleman: "der Tutor", espanol: "el tutor"},
{aleman: "die Tutorin", espanol: "la tutora"},
{aleman: "üblich", espanol: "común"},
{aleman: "hinterher", espanol: "después"},
{aleman: "eindeutig", espanol: "claro/a (claramente)"},
{aleman: "die Konferenz", espanol: "la reunión"},
{aleman: "die Leitung", espanol: "la dirección"},
{aleman: "gleichberechtigt", espanol: "con los mismos derechos"},
{aleman: "mitbestimmen", espanol: "participar (en la toma de una decisión)"},
{aleman: "die Sportanlage", espanol: "la instalación deportiva"},
{aleman: "sodass", espanol: "de manera que"}
]
    },
                {
      id: 12,
      nombre: "leccion 12 ",
      palabras:[
{aleman: "das Porträt", espanol: "el retrato"},
{aleman: "sprayen", espanol: "pintar (dibujar, con spray)"},
{aleman: "das Graffito", espanol: "el grafiti"},
{aleman: "der Song", espanol: "la canción"},
{aleman: "die Kunstform", espanol: "la forma de arte"},
{aleman: "gewöhnlich", espanol: "común"},
{aleman: "die Couch", espanol: "el sofá"},
{aleman: "das Gedicht", espanol: "el poema"},
{aleman: "der Vordergrund", espanol: "el primer plano"},
{aleman: "der Hintergrund", espanol: "el fondo"},
{aleman: "vorne", espanol: "delante"},
{aleman: "als ob", espanol: "como si"},
{aleman: "erkennen", espanol: "reconocer"},
{aleman: "der Strich", espanol: "la raya (la línea)"},
{aleman: "die Fotografie", espanol: "la fotografía"},
{aleman: "Ich habe es eilig.", espanol: "Tengo prisa."},
{aleman: "sich benehmen", espanol: "portarse"},
{aleman: "je ... desto", espanol: "cuanto más... más"},
{aleman: "die Literatur", espanol: "la literatura"},
{aleman: "der Autor", espanol: "el autor"},
{aleman: "die Autorin", espanol: "la autora"},
{aleman: "die Malerei", espanol: "la pintura"},
{aleman: "die Zeichnung", espanol: "el dibujo"},
{aleman: "der Film", espanol: "el cine (la película)"},
{aleman: "der Sänger", espanol: "el cantante"},
{aleman: "die Sängerin", espanol: "la cantante"},
{aleman: "das Theaterstück", espanol: "la obra de teatro"},
{aleman: "die Skulptur", espanol: "la escultura"},
{aleman: "schreiben", espanol: "escribir"},
{aleman: "der Roman", espanol: "la novela"},
{aleman: "die Oper", espanol: "la ópera"},
{aleman: "sich interessieren für", espanol: "interesarse por"},
{aleman: "klingen", espanol: "sonar"},
{aleman: "die Lyrik", espanol: "la lírica (la poesía)"},
{aleman: "die bildende Kunst", espanol: "las artes plásticas"},
{aleman: "erstaunlich", espanol: "sorprendente"},
{aleman: "sich langweilen", espanol: "aburrirse"},
{aleman: "das Ballett", espanol: "el ballet"},
{aleman: "die Vernissage", espanol: "la inauguración (de una exposición)"},
{aleman: "berühmt", espanol: "famoso/a"},
{aleman: "der Komponist", espanol: "el compositor"},
{aleman: "die Komponistin", espanol: "la compositora"},
{aleman: "die Uraufführung", espanol: "el estreno mundial"},
{aleman: "das Meisterwerk", espanol: "la obra maestra"},
{aleman: "die Melodie", espanol: "la melodía"},
{aleman: "die Komödie", espanol: "la comedia"},
{aleman: "der Schauspieler", espanol: "el actor"},
{aleman: "die Schauspielerin", espanol: "la actriz"},
{aleman: "das Schlagzeug", espanol: "la batería (instrumento)"},
{aleman: "die Klarinette", espanol: "el clarinete"},
{aleman: "der Witz", espanol: "el chiste"},
{aleman: "die Bühne", espanol: "el escenario"},
{aleman: "sich amüsieren", espanol: "divertirse"},
{aleman: "das Publikum", espanol: "el público"},
{aleman: "die Vorstellung", espanol: "la función (representación)"},
{aleman: "die Zunge", espanol: "la lengua"},
{aleman: "auf der Zunge liegen", espanol: "tenerlo en la punta de la lengua"},
{aleman: "vervollständigen", espanol: "completar"},
{aleman: "verlegen", espanol: "avergonzado/a"},
{aleman: "mitlaufen", espanol: "ir con (seguir)"},
{aleman: "ausspucken", espanol: "escupir (echar)"},
{aleman: "ratlos", espanol: "sin saber qué hacer"},
{aleman: "betrachten", espanol: "mirar"},
{aleman: "die Schneeflocke", espanol: "el copo de nieve"},
{aleman: "die Station", espanol: "la parada"},
{aleman: "zusperren", espanol: "cerrar (con llave)"},
{aleman: "sich die Hände reiben", espanol: "frotarse las manos"},
{aleman: "sich schütteln", espanol: "sacudirse"},
{aleman: "rumstehen", espanol: "estar parado (de pie, sin propósito)"},
{aleman: "sich verkühlen", espanol: "resfriarse"},
{aleman: "womöglich", espanol: "posiblemente"},
{aleman: "still", espanol: "en silencio"},
{aleman: "schließlich", espanol: "finalmente"},
{aleman: "der Prachtbau", espanol: "el edificio (impresionante, muy bonito)"},
{aleman: "entfernt", espanol: "alejado/a"},
{aleman: "der Schornstein", espanol: "la chimenea"},
{aleman: "verrückt", espanol: "loco/a"},
{aleman: "weder ... noch", espanol: "ni ... ni"},
{aleman: "der Mülleimer", espanol: "la papelera"},
{aleman: "spazieren gehen", espanol: "dar un paseo"},
{aleman: "die Ahnung", espanol: "la idea (el conocimiento)"},
{aleman: "der Waggon", espanol: "el vagón"},
{aleman: "die Gabel", espanol: "el tenedor"},
{aleman: "die Ausstellung", espanol: "la exposición"},
{aleman: "einerseits ... andererseits", espanol: "por un lado ... por otro lado"},
{aleman: "die Aufführung", espanol: "la representación (la función)"},
{aleman: "der/die Einheimische", espanol: "el/la lugareño/a (el/la nativo/a)"},
{aleman: "beeindrucken", espanol: "impresionar"},
{aleman: "die Überlegung", espanol: "la consideración (la reflexión)"},
{aleman: "aufwendig", espanol: "costoso/a (en tiempo/esfuerzo)"}
]
    },
    {
      id: 13,
      nombre: "Reisen und Urlaub",
      palabras: [
        { aleman: "die Übernachtung", espanol: "la pernoctación"},
        { aleman: "sich erholen", espanol: "recuperarse" },
        { aleman: "das Zeichen", espanol: "el signo" },
        { aleman: "tauchen", espanol: "bucear" },
        { aleman: "die Wüste", espanol: "el desierto" },
        { aleman: "buchen", espanol: "reservar" },
        { aleman: "leider", espanol: "lamentablemente" },
        { aleman: "vorbei sein", espanol: "haber terminado" },
        { aleman: "feiern, feierte, hat gefeiert", espanol: "celebrar" },
        { aleman: "fotografieren, fotografierte, hat fotografiert", espanol: "fotografiar" },
        { aleman: "die Reise", espanol: "el viaje" },
        { aleman: "probieren, probierte, hat probiert", espanol: "probar" },
        { aleman: "surfen, surfte, hat gesurft", espanol: "hacer surf" },
        { aleman: "das Abenteuer", espanol: "la aventura" },
        { aleman: "der Urlaub", espanol: "las vacaciones" },
        { aleman: "der Flug", espanol: "el vuelo" },
        { aleman: "der Reiseführer", espanol: "guía de viajes" },
        { aleman: "zu Fuss", espanol: "a pie" },
        { aleman: "die öffentlichen Verkehrsmittel", espanol: "los medios de transporte público" },
        { aleman: "unterwegs sein", espanol: "estar de camino" },
        { aleman: "die Bahn", espanol: "los ferrocarriles" },
        { aleman: "der Sparpreis", espanol: "el precio reducido" },
        { aleman: "das Bahnticket", espanol: "el billete de tren" },
        { aleman: "der Zug", espanol: "el tren" },
        { aleman: "weit", espanol: "lejos" },
        { aleman: "die Studienreise", espanol: "viaje de estudios" },
        { aleman: "das Jugendgästehaus", espanol: "el hostal juvenil" },
        { aleman: "die Bettwäsche", espanol: "la ropa de cama" },
        { aleman: "warten auf, wartete auf, hat gewartet auf", espanol: "esperar a" },
        { aleman: "die Reservierung", espanol: "la reserva" },
        { aleman: "der Bus", espanol: "el autobús" },
        { aleman: "die U-Bahn", espanol: "el metro" },
        { aleman: "draußen", espanol: "dentro" },
        { aleman: "pünktlich", espanol: "puntual" },
        { aleman: "der Ausweis!", espanol: "el carnet" },
        { aleman: "rechtzeitig", espanol: "a tiempo" },
        { aleman: "die Anreise", espanol: "el viaje de ida" },
        { aleman: "wecken, weckte, hat geweckt", espanol: "despertar" },
        { aleman: "die Abreise.", espanol: "el viaje de vuelta" },
        { aleman: "der Wohnsitz", espanol: "lugar de residencia" },
        { aleman: "verienbaren", espanol: "concertar" },
        { aleman: "froh", espanol: "contento" },
        { aleman: "die Ankuftszeit", espanol: "hora de llegada" },
        { aleman: "der Platz", espanol: "el sitio" },
        { aleman: "freihalten", espanol: "mantener libre" },
        { aleman: "die Unterbringung", espanol: "el alojamiento" },
        { aleman: "grundsätzlich", espanol: "basicamente" },
        { aleman: "weiblich", espanol: "femenino" },
        { aleman: "männlich", espanol: "masculino" },
        { aleman: "vorgeschrieben", espanol: "establecido" },
        { aleman: "sogar", espanol: "incluso" },
        { aleman: "zustimmen", espanol: "aceptar" },
        { aleman: "der Stock , die Etage", espanol: "la planta" },
        { aleman: "notwendig", espanol: "necesario" },
        { aleman: "verliebt sein", espanol: "estar enamorado" },
        { aleman: "das Gelände", espanol: "el área" },
        { aleman: "der Flur", espanol: "el pasillo" },
        { aleman: "die Feuerwehr", espanol: "los bomberos" },
        { aleman: "schriftlich", espanol: "por escrito" },
        { aleman: "die Not", espanol: "la urgencia" },
        { aleman: "der Koffer", espanol: "la maleta" },
        { aleman: "die Teilnahme", espanol: "la participación" },
        { aleman: "anbieten, bot an, hat angeboten", espanol: "ofrecer" },
        { aleman: "bitten, bat, hat gebeten", espanol: "pedir" },
        { aleman: "radeln", espanol: "montar en bici" },
        { aleman: "die Strecke", espanol: "el trayecto" },
        { aleman: "allein", espanol: "solo" },
        { aleman: "draußen", espanol: "afuera" },
        { aleman: "faulenzen", espanol: "vaguear" },
        { aleman: "der Feueralarm", espanol: "la alarma de incendio"},
        { aleman: "gefährlich sein", espanol: "ser peligroso"},
        { aleman: "das Wetter", espanol: "el tiempo" },
        { aleman: "in der Nähe", espanol: "cerca de" },
        { aleman: "der Flughafen", espanol: "el aeropuerto" },
        { aleman: "die Umgebung", espanol: "los alrededores" },
        { aleman: "der Flur", espanol: "el pasillo" },
        { aleman: "die Feuerwehr", espanol: "los bomberos" },
        { aleman: "entdecken", espanol: "descubrir" },
        { aleman: "der Passagier", espanol: "el pasajero" },
        { aleman: "die Warteschlange", espanol: "la cola de espera" },
        { aleman: "der Schalter", espanol: "la ventanilla" },
        { aleman: "der Stau", espanol: "el atasco" },
        { aleman: "das Gleis", espanol: "la vía" },
        { aleman: "der Bahnhof ", espanol: "la estación de tren" },
        { aleman: "ausfallen", espanol: "cancelar " },
        { aleman: "sich anschnallen", espanol: "fasten seat belts" },
        { aleman: "die Geschwindigkeit", espanol: "la velocidad"  },
        { aleman: "der Treffpunkt", espanol: "punto de encuentro" },
        { aleman: "die Panne", espanol: "la avería"},
        { aleman: "das Zelt", espanol: "la tienda de campaña"},
        { aleman: "die Herausforderung", espanol: "el reto" },
        { aleman: "per Anhalter fahren", espanol: "hacer autostop" },
        { aleman: "sich befinden", espanol: "hallarse" },
        { aleman: "die Burg", espanol: "el castillo" },
        { aleman: "sich verlaufen", espanol: "perder el camino" },
        { aleman: "halten", espanol: "detenerse" },
       
      ]
    },
               
  ]
};
